project:
  type: manuscript
  render:
    - "*.qmd"
    - "!data-raw/"

execute:
  freeze: auto

format:
  html:
    toc: true
    comments:
      hypothesis: true
  pdf:
    notebook-links: false
    keep-tex: true
  docx: 
    notebook-links: false
    footnotes-to-endnotes: true



